//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerDetail
    {
        public long Owner_detail_No { get; set; }
        public int Owner_No { get; set; }
        public string Item_Name { get; set; }
        public int QTY { get; set; }
    }
}
